.dockerignore
.drone.yml
Dockerfile
README.md
kube/deployment.yml
kube/ingress.yml
kube/service.yml
package-lock.json
package.json

Merge required to get Drone config into master

Added drone, docker and k8s config

---

.drone.yml
Dockerfile
README.md
kube/deployment.yml
kube/ingress.yml
kube/network-policy.yml
kube/secret.yml
models/datasets.js

- Docker now runs as non-root
- Added keycloak
- Integrated Lets Encrypt certs
- Drone updated to also include prod deployment
- Added session table to db startup checks

Completed docker and kubernetes config

---

Dockerfile

Updates user id

---

controllers/items.js
models/items.js
test/config.js

Implements fetchall for backend

Implements fetchall for backend

---

controllers/items.js

Makes json request type to fetch all data

Makes json request type to fetch all data

---

Dockerfile
kube/deployment.yml

Updates container security issue for BDM

Updates container security issue for BDM

---

kube/ingress.yml

added annotation to maintain secure connections following kube platform upgrade

added annotation to maintain secure connections

---

.drone.yml
app.js
config/core.js
kube/deployment.yml

1) Only displaying errors that are alright to be viewed in prod
2) Redirects stack traces to log and brings user back to home page
3) Removes environment variable set that confuses with NODE_ENV which is the one node uses by default

Secures application by:

---

routes.js
views/getDatasets.html
views/getItems.html

Remove dataset names from 2 title bars 
Remove type of id and fields columns from main tables page
Change view button to say data 
Change manage button to say edit

Remove individual datasets from header

---

views/getItems.html

Prevent tables from displaying more than 6 columns

BT-1234: #time 2h Change tables to display a max of 6 columns

---

controllers/items.js
models/items.js
public/javascripts/pagination-helper.js
test/models/items.js
views/getItems.html
views/layout.html
views/partials/pagination.html

Add search functionality to datasets
- Allows users to search varchar and integer fields 
- Provides results with pagination

BT-1224 10h Adds search functionality to datasets

---

models/items.js

Change search functionality to not use query params for which a column does not exist

BT-1224 1H 00M Change search query to not use columns that do not exist

---

controllers/items.js
models/item.js
models/items.js
test/models/item.js
test/models/items.js
views/getItem.html
views/getItems.html

- Quote column names on all operations to allow for spaces
- Fix application compatibility with date types
- Add additional error handling to create and edit routes
- Resolve editing issues for tables with serial ids
- Group tests by functionality

BT-1239 8H 00M Fix item create and edit

---

Dockerfile
package-lock.json
package.json

Update base image to use node-10 
Update packages which require node 10+

Update dockerfile base to node-10, update all packages

---

kube/deployment.yml

Reverts UKHomeOffice/business-data-manager#42

Revert "add gatekeeper container"

---

README.md
package.json
yarn.lock

Updates readme and pg NPM package version

Updates readme and pg NPM package version

---

.drone.yml
kube/dq-staging-rds-secret.yml

Deploy staging

---

controllers/items.js
lib/utils.js
models/items.js
views/getDatasets.html
views/getItem.html
views/getItems.html

Cor 2744 version history

---

app.js
controllers/datasets.js
controllers/items.js
lib/Authenticator.js
lib/validator.js
models/dataset.js
views/getDataset.html
views/getItem.html

Add validation to item add/update

Cor 2792 validation

---

.nvmrc
Dockerfile

- Set node version to Node 16
- Use node 16 for dockerfile

Patch BDM and update to node 16

---

models/item.js

This reverts commit 1982a16ff61174f6577406a789ef6fd5f68e59e2.

Revert "Fix ports not allowing me to add a new port"

---

README.md

Updates the documentation

---

.nvmrc
README.md
mise.toml

Updates the documentation and configuration to better suit linux

Updates documentation and configuration
